[package]
name = "py-bcndecode"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap = "0.7"
bcndecode = { path = "bcndecode" }

[lib]
name = "py_bcndecode"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module", "abi3"]